authtoken: 1f8dCTISUhNZfMh9d8V1jFZ8Kb8_2isty23kEfMKh1LepPruw
region: ap
web_addr: 0.0.0.0:4444
log_level: debug
log: stdout

tunnels:
    vnc:
        proto: tcp
        addr: 51252
        remote_addr: 0.tcp.ap.ngrok.io:51252