#!/usr/bin/env bash

port=${1:-${PORT:-8080}}

if [ -z "$NGROK_API_TOKEN" ]; then
  echo "You must set the NGROK_API_TOKEN config var to create a TCP tunnel!"
  exit 1
fi

# Starting Screen
limit=$(ulimit -u)
case $limit in
  512)   # 2X Dyno
  heap="768m"
  ;;
  32768) # PX Dyno
  heap="4g"
  ;;
  *)     # 1X Dyno
  heap="384m"
  ;;
esac

echo "Starting Screen"
eval "screen -L -h 2048 -dmS 1"
main_pid=$!

# Start VNC server
umask 0077                                        # use safe default permissions
chmod go-rwx "$HOME/.vnc"                         # enforce safe permissions
vncpasswd -f <<<"123456" >"$HOME/.vnc/passwd"  # generate and write a password

vnc_cmd="vncserver -geometry 1366x768 -depth 24"
echo "Start VNC server..."
eval $vnc_cmd
vnc_pid=$!

# Start the TCP tunnel
ngrok_cmd="bin/ngrok tcp -authtoken $NGROK_API_TOKEN -log stdout --log-level debug tcp 5901 -config=bin/ngrok.conf"
echo "Starting ngrok..."
eval "$ngrok_cmd | tee ngrok.log &"
ngrok_pid=$!

# Flush the logfile every second, and ensure that the logfile exists
screen -X "logfile 1" && sleep 1
echo "Tailing log"
eval "tail -f screenlog.0 &"
tail_pid=$!

trap "kill $vnc_pid $ngrok_pid $main_pid $tail_pid" SIGTERM
trap "kill -9 $vnc_pid $ngrok_pid $main_pid $tail_pid; exit" SIGKILL

eval "ruby -rwebrick -e'WEBrick::HTTPServer.new(:BindAddress => \"0.0.0.0\", :Port => ${port}, :MimeTypes => {\"rhtml\" => \"text/html\"}, :DocumentRoot => Dir.pwd).start'"
